version: '2'
services:
    boom-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/booM/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=booM
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
